### ISSUE TITLE
Importing qwik-slider affecting the styiling of other components

### ISSUE THREAD

**Issue by vishnued** [pheno-agency/qwik-slider#5]
Hi, 
I have imported the qwik-slider and it's affecting the styling of other components in my app. 
I think it's because of the useStyles$, we may need to use the useStylesScoped$().

**Comment by AmirSa12** [comment]
Hi, Thank you for opening the issue and bringing this to our attention. I will solve this in the next version and let you know here.
Thank you for using qwik-slider, and we appreciate your feedback!

**Comment by AmirSa12** [comment]
@vishnued , now qwik-slider should not affect other component's styles. please tell me if the issue remains otherwise let's close this issue.

**Comment by vishnued** [comment]
@AmirSa12 we can close this, its working as expected.

**Comment by AmirSa12** [comment]
> @AmirSa12 we can close this, its working as expected.

@vishnued , Thank you!
