### ISSUE TITLE
The sider doesn't work

### ISSUE THREAD

**Issue by alihammad99** [pheno-agency/qwik-slider#6]
I've tried to use this package and here's the code:

```
import { component$ } from "@builder.io/qwik";
import { Slider } from "qwik-slider";

export default component$(() => {
  return (
    <div>
      <Slider>
        <div class={styles.card}>Card 1</div>
        <div class={styles.card}>Card 2</div>
        <div class={styles.card}>Card 3</div>
        <div class={styles.card}>Card 3</div>
        <div class={styles.card}>Card 3</div>
        <div class={styles.card}>Card 3</div>
      </Slider>
    </div>
  );
});
```

The result attached as below photo

![Screenshot (423)](https://github.com/pheno-agency/qwik-slider/assets/59452488/5d184155-d036-4988-b48c-36ac62965ed6)

**Comment by AmirSa12** [comment]
@alihammad99 Thanks for reaching out! The slider works fine, the problem with your code is that you have not applied settings for your slider container. in this case, your slider container does not have a width. try applying some settings and let me know! 
Here is an example:
```ts
const sliderSettings = {
    scrollSpeed: 1,
    gap: 50,
    showScrollbar: false,
    autoScroll: true,
    autoScrollSpeed: 5,
    width: "300px",
  };
  ```
  and apply it it to your slider container:
  ```ts
  // ...
   <Slider {...sliderSettings}>
     // ...
   </Slider>
  ```

**Comment by alihammad99** [comment]
It worked thank you, I had to add min-width to the card as well.

**Comment by netzpixel** [comment]
I basically have the same issue. Is there any example page of what the slider is supposed to do? What I'm trying to archive is a classic carousel with one slider visible at a time but I can't find a way to get that.

**Comment by AmirSa12** [comment]
> I basically have the same issue. Is there any example page of what the slider is supposed to do? What I'm trying to archive is a classic carousel with one slider visible at a time but I can't find a way to get that.

@netzpixel , there is a link in the description, https://stackblitz.com/edit/qwik-starter-ymbcrd .
What you are trying to achieve is still not supported, working on it.

**Comment by netzpixel** [comment]
Ah I see. Thanks for the qwik response :)
